### ISSUE TITLE
feat: enable autoscaling

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-azurerm-web-app#86]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_autoscale_setting

**Comment by sebastianlolv** [comment]
![image](https://user-images.githubusercontent.com/43113824/226577659-c8daa02f-c1c6-4296-9dd6-6deedc943066.png)

Since setting capacity block is required, what should the maximum and minimum values be? 

The example sets Default to 1, minimum to 1 and maximum to 10.
